### ISSUE TITLE
Care Team Orga

### ISSUE THREAD

**Issue by sr189** [rughh/ruby-unconf#13]
Care Team Setup with @filtercake.

The Care Team will be responsible for enforcing the CoC, will be around to be directly contacted, will monitor the talks and things like twitter.

**Comment by halfbyte** [comment]
Had a productive call with @filtercake today. Here's what I've written down, feel free to add stuff I missed, Fabian

- We'll need a team of 3-4 people (1+1 for the rooms, 1 extra, ideally 1 backup-backup), it's probably a good idea if one of the main organizers is part of the team (I would like to do that)
  - [x] Fabian (will hopefully confirm attendence next week)
  - [x] @halfbyte (I would be backup-backup and responsible for interactions with, for example,sponsors and vendors if needed)
  - [x] @sssggr 
  - [x] @susannekaiser 
- It's good to have an intro slot in the beginning of the conference so that everyone is clear on how this thing works and what the purpose is. (@filtercake will share the text they used at Jeffconf)
  - @sssggr and @filtercake will do the intro, as @halfbyte will do the conf intro
- [ ] @filtercake will try to find some ugly caps to make us recognisable.
- [ ] @halfbyte will add slide to intro contact data 
- [x] We'll need a "burner phone", a phone with a prepaid SIM card so that nobody has to publish their private mobile number. @halfbyte has a relatively recent Nokia Feature Phone we can use for that. Ok, done. Number is tel:+49-176-98-71-78-41, phone works.
- [ ] The care team needs an email address (care@rubyunconf.eu) - @halfbyte will set that up
- [ ] We'll need a couple of posters with the care team contact data. 
- [ ] Before the conference, the whole core team + helpers should be briefed by the care team.
- [ ] @filtercake preps a short text to send to all helpers (text => jan)
- [x] Party plan
  - early shift: @sssggr 
  - late shift @halfbyte
- [ ] Signal-Groupchat: @sssggr creates it and invites everyone.
- Setup at the conference
  - Saturday: ~ 8:00 Meetup, 
  - Setup Rooms (specifically Dietze could be a bit tricky, Forum should be easy)

**Comment by afknapping** [comment]
Hi all 👋

This the text we read at the intro at jeffconf...

—-

(Brief intro of team and contact info)



The point is not to keep you from saying or thinking specific things

The point is to keep it from happening *here*, and the after-party, *today*

this event is supposed to be a safe space for everyone who is here, and we need your help for thay

This is a “community event”

What does community mean?

it means that it’s not about you

It means always behaving in good intent and having the well-being of all others community members as highest priority

You cannot know what makes another person feel bad. That’s why we explicitly listed topics and behaviours to avoid. This is meant as as help to you, to not accidentally hurt someone

[...] gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, ethnicity, religion (or lack thereof), or technology choices.

Ok. But what if it happens. What if you accidentally hurt someone?
There are usually two types of behaviours after such a mistake

A) You get it, welcome the feedback, aapologise and accept the consequences if there are any

B) You get defensive and emotional, insisting that you didn’t mean it and that in turn you shouldn’t have to bear any consequences. Or worse: that you are right and should be allowed to continue

Why you defend your right to make another person feel shitty?

DON’T DO THAT!

Take care of the people around you!

Speak up if you hear someone making sexist, racist, or otherwise inapprioate remarks!

Not for you. For those around you. 

if you cannot or don’t want to do that or especially if you feel hurt, talk to us. That’s what we’re here for.

We want to **avoid** incidents!

A lot of incidents at conferences could have been avoided if people had gotten feedback earlier

We want to *avoid* incidents, and early feedback is the best way to do that

anything you share with us is treated confidentially

Our goal is to make this a great day for *everyone* who is here — and we hope that this your goal too :)

And now, let’s watch some great talks!

**Comment by halfbyte** [comment]
@filtercake Nina @sssggr (we've talked about me asking her) agreed to help. She told me she doesn't like the name "Care Team", but I'll let her argue for herself. Adding her in here so that she can join the discussion.

**Comment by sssggr** [comment]
Hi @halfbyte and @filtercake, happy to join you! I wouldn't say that I don't like the name, but I haven't heard it before and would like to understand it better. If one of you could provide me some background info that would be amazing. 

Do you have another call scheduled? Which communication channel(s) do you use?

**Comment by afknapping** [comment]
hey @sssggr 👋

"care team" was the name at RuhrJS. I really liked it because it puts the team into a more positive/constructive/pro-active point of view – away from "reactiing to CoC violations" into "we care about community and everyone in it".

**Comment by sssggr** [comment]
@filtercake: okay, thanks for the background info!

**Comment by afknapping** [comment]
> Fabian will ask Susanne who was part of the Jeffconf care team

can finally move that to "done", update incoming...

**Comment by halfbyte** [comment]
@filtercake We're very curious :)

**Comment by halfbyte** [comment]
@filtercake In all seriousness, I'd love to know: 
- If you'll make it
- if you found someone else to join the team
- If we all should probably do a skype call late next week or early CW18 or even meet up if possible.

**Comment by afknapping** [comment]
ah, apologies.

> can finally move that to "done", update incoming...

yes, @susannekaiser answered she can help out with the coc team that weekend (thx susanne!)

and i'll make it yes :)

call seems like a good idea, i made a doodle: https://doodle.com/poll/pi8z8qyzze6nmuei

**Comment by sssggr** [comment]
Hi @susannekaiser! +1 for the call and thanks for setting up the doodle. It says 07:30 am but I assume you don't want to meet that early and we are talking about 07:30 pm @filtercake?

**Comment by afknapping** [comment]
> It says 07:30 am but I assume you don't want to meet that early and we are talking about 07:30 pm @filtercake?

yes, fixed :)

**Comment by susannekaiser** [comment]
Hi all, sorry for my late response. My notifications of this thread went to /dev/null ... kind of. I finally filled out the doodle, too.

**Comment by afknapping** [comment]
@susannekaiser no problem, thx for helping out here!

i chose sunday april 29 19:30 for the call. @susannekaiser that's one the days you're not available – we'll post a log here :)

proposed agenda for the call:
- run through the [task list above](#issuecomment-371524728)
- assign tasks
- add missing tasks and split into specifics so we can get stuff marked as done.

example:
> Before the conference, the whole core team + helpers should be briefed by the care team.

That could mean:

- prep a document (who writes it, what is in it, where is it, who needs to get it,...)
- make sure everyone has a day or two before the weekend to read it (means a deadline 😱 on wednesday or something)
- block a short briefing and QA round for core team and helpers (eg 20 min timeblock an hour before doors open)

--- 

we can also collect those things here in the open until the call of course...

**Comment by afknapping** [comment]
Let’s meet in https://appear.in/rubyunconf at 19:30. See you then :)

**Comment by halfbyte** [comment]
@susannekaiser I've tried to update the Todo list above - It should roughly cover everything we've talked about.

**Comment by halfbyte** [comment]
@susannekaiser @filtercake @sssggr Could y'all send me an email to jan@krutisch.de with the email address you want me to use for the Email forward?

**Comment by halfbyte** [comment]
I've added the full contact info to the website and extracted it to a separate page (for easier linking from a QR code and a poster) and also added anonymous form submits (using formspree, these will end up in our email inbox as well). Any objections?

**Comment by halfbyte** [comment]
All, here's a first shot at a possible poster design. Please let me know what you think: 

https://drive.google.com/open?id=1qr1HKrixJYh3tZxFd7e9GHooIPDvDz7r

Unfortunately, I didn't manage to do that in a google doc, so it is a Pages document :(

**Comment by afknapping** [comment]
> All, here's a first shot at a possible poster design. Please let me know what you think:

<3 👍

**Comment by afknapping** [comment]
here's a first draft for the team briefing. I'm not exactly in a relaxed mood tonight, so feel free to edit away... all feedback welcome...

---

Dear Volunteers and core team members.

This a quick briefing from the Care Team on **how to handle Code of Conduct related things.** We will try to catch all of you shortly on Saturday morning to adress any questions – also feel free to mail back or call us of course :)

- please re-read the code of conduct at url carefully – at least once
- at url you can find the draft of a short note we will give during the introduction. please read that too
- what goes for every attendee, goes for you too: please speak up if you become aware of inapropriate behaviour or contact the Care Team

**What should I do when an attendee approaches me and wants to report something?**

- keeping the person safe is priority 1. Do not leave their side and block away anybody else (including other team members) except the ones they explicitly invite into the situation. Stay calm, keep quiet, be discrete.
- Tell them you will call the Care Team and that someone will be with them shortly.
- do *not* ask them what happened or give the impression you’re taking a report – that is what we are there for :)
- if they need to speak about what happened, let them do so, but make sure nobody else is eavesdropping and keep in mind all of that is highly confidential
- stay with them and guide the two of you out of any group setting. A quite corner out of sight or a separate room are best.
- ask them if they need anything (water, food, a quiet place to rest)
- Let us know where you are via the official phone nr 12345678890 or via our personal numbers (12345678890, 12345678890, 12345678890, 12345678890). Also mention if we should bring something and what else is needed for the person
- Wait until one of us arrives.
- Again: keeping them safe and guarded is priority 1.

This might sound a bit alarming and overboard to some of you. The tl;dr is that you might deal with a person who has just been triggered into a severe past trauma. While that is rare in absolute numbers, it *has* happened at other confs and it's best to assume worst case at first to avoid adding insult to injury. Staying calm and assuring, and keeping the person safe is the best and most important you can do at first.

Worry not – we're here for you too! You are welcome and encouraged to address all questions on this to us via call, mail or in person on Saturday.

Thanks for your help! Let’s have an incident-free event where every single person has a good time :)

Best,
The Care Team: Nina, Susanne, Jan and Fabian

**Comment by afknapping** [comment]
the panels we used at https://tweetdeck.twitter.com/ for monitoring at jeffconf:

![image](https://user-images.githubusercontent.com/170145/39599133-1a93a274-4f1b-11e8-9246-314dcf1da444.png)

serch term was `jeffconfhamburg OR jeffconf OR @jeffconf`

I also had a panel with DMs open, since we had that as a channel too.

here is an example exchange I had on twitter:

![image](https://user-images.githubusercontent.com/170145/39599332-cad28538-4f1b-11e8-8dfe-1fa4f0cfc508.png)

**Comment by afknapping** [comment]
public url of intro text google doc is https://docs.google.com/document/d/1I21PhLZU-1tPL_cX0xFr4-4X9Kf040RszsDqpRGafts/
